version: '3.8'

services:
  llamacpp:
    image: joshxt/local-llm:cpu
    environment:
      - LOCAL_LLM_API_KEY=${LOCAL_LLM_API_KEY-}
    restart: unless-stopped
    ports:
      - "8091:8091"
    volumes:
      - ./models:/app/models